import type { Metadata } from "next";
// import { Inter } from 'next/font/google'
import { exo2 } from "@/utils/fonts";
import "./globals.css";

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={exo2.className}>
        {/* <nav className="px-10 py-5 bg-primary  shadow-sm">
          <h1 className="text-white">Equation Solver</h1>
        </nav> */}
        {children}
      </body>
    </html>
  );
}
